import { Projeto } from '@/types'

export const INITIAL_MOCK_PROJETOS: Projeto[] = [
  {
    id: '1',
    slug: 'identidade-visual-ucadis',
    titulo: 'UCADIS',
    cliente: 'Arquitetura de Marca Monolítica e Design Ops',
    categoria: 'design_ops',
    diagnostico: 'Arquitetura de Marca Monolítica e Design Ops',
    processo: 'Desenvolvimento de manual de identidade visual, design ops, matriz cromática, sinalização wayfinding e mascotes.',
    resultado: 'Escalabilidade operacional e autonomia para equipes descentralizadas.',
    imagens: [],
    imagem_capa: '/images/ucadis-capa-mascotes.png',
    video_url: null,
    ordem: 1,
    publicado: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    slug: 'jing-long',
    titulo: 'Jing Long Martial Arts Academy',
    cliente: 'Redesign de Suporte e Extensão de Marca Híbrida',
    categoria: 'design_ops',
    diagnostico: 'Redesign de Suporte e Extensão de Marca Híbrida',
    processo: 'Desenvolvimento de Design Tokens, sistema cromático, matriz tipográfica e desdobramento em vestuário e produtos.',
    resultado: 'Identidade forte e consistente, unificando vestuário, equipamentos e linha proprietária.',
    imagens: [],
    imagem_capa: '/images/jing-long-hero-cover.png',
    video_url: null,
    ordem: 2,
    publicado: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    slug: 'eb-escola-de-musica',
    titulo: 'EB Escola de Música',
    cliente: 'Design de Identidade Local',
    categoria: 'sistemas_identidade',
    diagnostico: 'A falta de padronização visual reduzia a taxa de conversão de novos leads e enfraquecia o diferencial competitivo de mercado. O desafio consistiu em estruturar um sistema visual que tangibilizasse a metodologia e acelerasse a jornada de decisão do aluno.',
    processo: 'Estruturação de marca e sistema visual voltado ao ensino musical e presença local.',
    resultado: 'Identidade memorável e forte posicionamento na comunidade.',
    imagens: [],
    imagem_capa: '/og-image.png',
    video_url: null,
    ordem: 3,
    publicado: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '4',
    slug: 'francis-pinheiro-seguros',
    titulo: 'Francis Pinheiro Seguros',
    cliente: 'Go-To-Market, Mídia de Performance & WhatsApp Ops',
    categoria: 'sistemas_identidade',
    diagnostico: 'O desafio consistia em introduzir uma nova corretora de seguros no mercado a partir do zero absoluto, estabelecendo autoridade instantânea em um setor altamente regulado. Para garantir tração imediata, o projeto exigia uma abordagem integrada que superasse o escopo tradicional do design: era necessário construir um sistema de identidade visual robusto e, simultaneamente, desenhar a engenharia do funil comercial — alinhando os criativos de tráfego pago à régua de relacionamento automatizada no WhatsApp, mitigando o atrito na captação de leads frios.',
    processo: 'Service Design: Integração entre Identidade (Brand Equity Institucional), Mídia de Performance (matrizes de criativos focados em conversão e CTR) e Desenho de Serviço (WhatsApp Ops com réguas automatizadas e roteiros de abordagem).',
    resultado: 'A entrega consolidou a introdução da corretora no mercado com uma estrutura corporativa madura, escalável e orientada a dados. O alinhamento entre a identidade visual e o fluxo do WhatsApp gerou previsibilidade comercial, otimizou o Custo por Lead (CPL) e blindou a marca com diretrizes prontas para a expansão futura da equipe de vendas.',
    imagens: [],
    imagem_capa: '/og-image.png',
    video_url: null,
    ordem: 4,
    publicado: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '5',
    slug: 'jo-quitutes',
    titulo: 'Jô Quitutes',
    cliente: 'Identidade Visual e Posicionamento',
    categoria: 'sistemas_identidade',
    diagnostico: 'Identidade Visual e Posicionamento',
    processo: 'Criação de universo visual gastronômico e embalagens proprietárias.',
    resultado: 'Reconhecimento de marca e valorização percebida do produto.',
    imagens: [],
    imagem_capa: '/og-image.png',
    video_url: null,
    ordem: 5,
    publicado: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '6',
    slug: 'jennifer-lemos-fotografia',
    titulo: 'Jennifer Lemos Fotografia',
    cliente: 'Identidade Visual e Posicionamento',
    categoria: 'sistemas_identidade',
    diagnostico: 'Identidade Visual e Posicionamento',
    processo: 'Construção de marca sofisticada e minimalista para fotografia autoral.',
    resultado: 'Diferenciação no mercado e alinhamento com clientes de alto valor.',
    imagens: [],
    imagem_capa: '/og-image.png',
    video_url: null,
    ordem: 6,
    publicado: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '7',
    slug: 'vocal-renascer-adbh-industrial',
    titulo: 'Vocal Renascer & ADBH Industrial',
    cliente: 'Direção de Arte e Esteiras de Produção de Alta Frequência',
    categoria: 'direcao_arte',
    diagnostico: 'Direção de Arte e Esteiras de Produção de Alta Frequência',
    processo: 'Sistema integrado de direção de arte para mídias sociais e esteiras de produção contínua.',
    resultado: 'Alta consistência visual e ritmo de publicação otimizado sem perda de qualidade.',
    imagens: [],
    imagem_capa: '/og-image.png',
    video_url: null,
    ordem: 7,
    publicado: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]
